### API error 404
GET http://localhost:3000/api/sqdqsd

### get all books
GET http://localhost:3000/api/books

### get on book
GET http://localhost:3000/api/books/1

### add book
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "isbn": "9781234567899",
    "original_title": "the handmaid's tale",
    "title": "La servante écarlante",
    "excerpt": "La servante écarlante n'était pas bleu",
    "publication_date": 1985,
    "language": "FR",
    "page_count": "300",
    "cover": "http://image.cover.com/tale.jpg",
    "publisher_id": 1
}

### update inétgral book
PUT http://localhost:3000/api/books/12
Content-Type: application/json

{
    "isbn": "9781234567899",
    "original_title": "the handmaid's tale",
    "title": "La servante écarlante",
    "excerpt": "La servante écarlante n'était pas bleu mais rouge",
    "publication_date": 1985,
    "language": "FR",
    "page_count": "300",
    "cover": "http://image.cover.com/tale.jpg",
    "publisher_id": 1
}

### update partiel book
PATCH http://localhost:3000/api/books/12
Content-Type: application/json

{
    "excerpt": "La servante écarlante n'était pas bleu mais carmin"
}


### update book qui marche pas
PUT http://localhost:3000/api/books/14
Content-Type: application/json

{
    "isbn": "9781234567899",
    "original_title": "the handmaid's tale",
    "title": "La servante écarlante",
    "excerpt": "La servante écarlante n'était pas bleu mais rouge",
    "publication_date": 1985,
    "language": "FR",
    "page_count": "300",
    "cover": "http://image.cover.com/tale.jpg",
    "publisher_id": 1
}

### delete book
DELETE http://localhost:3000/api/books/1